import Link from "next/link";
import { ArrowRight, Check, ChartLineUp, Certificate, MonitorPlay } from "@phosphor-icons/react/dist/ssr";
import { courses } from "@/data/courses";
import { CourseCard } from "@/components/CourseCard";

const wa = "https://wa.me/263778599227?text=Hello%20Fulcrum%2C%20I%27d%20like%20to%20book%20training.";
export default function Home() {
 return <main id="main">
  <section className="hero"><div className="hero-copy reveal"><span className="eyebrow">Fulcrum Consultancy & Training</span><h1>Turn data into <em>powerful insights.</em></h1><p>Practical Excel, Power BI, SQL and business systems training for people ready to put knowledge to work.</p><div className="actions"><Link className="button" href="/courses">Explore courses <ArrowRight /></Link><Link className="text-link" href="/contact">Book training</Link></div></div><DataLever /></section>
  <section className="trust-strip" aria-label="Training benefits"><span><Check /> Practical skills</span><span><Check /> Expert instructors</span><span><MonitorPlay /> Flexible learning</span><span><ChartLineUp /> Real projects</span><span><Certificate /> Certificates</span></section>
  <section className="section courses-home"><div className="section-intro"><span className="eyebrow">Popular training</span><h2>Build skills that move your career forward.</h2><p>Practical courses designed around tools businesses actually use.</p></div><div className="course-list">{courses.slice(0,3).map((c,i)=><CourseCard key={c.slug} course={c} featured={i===1}/>)}</div><Link className="text-link arrow-link" href="/courses">View all seven courses <ArrowRight /></Link></section>
  <section className="category-section section"><div className="category-title"><h2>One catalogue.<br/>Four ways forward.</h2><p>Choose the skill family that matches the work you want to do next.</p></div><div className="category-ledger"><div><b>Data & Analytics</b><span>Power BI / Excel / SQL</span></div><div><b>Accounting & Finance</b><span>QuickBooks / Pastel Partner</span></div><div><b>Payroll</b><span>Belina Payroll</span></div><div><b>Digital Skills</b><span>Computer applications</span></div></div></section>
  <section className="power-section section"><div className="power-copy"><span className="eyebrow">Power BI course</span><h2>Turn data into powerful insights.</h2><p>Learn how to connect, model, visualise and communicate data through hands-on exercises and real-world projects.</p><ul>{courses[1].topics.map(t=><li key={t}><Check />{t}</li>)}</ul><div className="price-lockup"><strong>US$85</strong><span>Course fee<br/>+ US$10 registration</span></div><Link className="button" href="/courses/power-bi">Register for Power BI <ArrowRight /></Link></div><div className="bi-visual" aria-label="Abstract Power BI dashboard showing rising business metrics"><div className="bi-head"><span>PERFORMANCE OVERVIEW</span><b>FULCRUM / BI</b></div><div className="bi-kpi"><small>Monthly output</small><strong>+28.4%</strong></div><div className="bar-chart">{[42,66,54,78,63,91,84].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div><div className="bi-note">FROM RAW DATA<br/><b>TO CLEAR DECISIONS</b></div></div></section>
  <section className="why section"><div className="why-lead"><h2>Why learn with Fulcrum?</h2><p>Every session is built to shorten the distance between knowing and doing.</p></div><div className="why-list">{[["Practical first","Hands-on sessions using real-world applications."],["Experienced instructors","Learn from professionals with industry experience."],["Flexible learning","Choose physical or online training."],["Real projects","Practise on realistic business scenarios."],["Certification","Certificates for eligible courses."],["Career value","Develop skills employers and businesses use."]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="audiences section"><h2>Training that meets you where you are.</h2><div className="audience-grid"><article><span>Students</span><h3>Build strong, in-demand skills for the future.</h3><Link href="/courses">Find your course <ArrowRight /></Link></article><article><span>Professionals</span><h3>Upgrade your skills and accelerate your career.</h3><Link href="/courses">Explore training <ArrowRight /></Link></article><article><span>Corporate teams</span><h3>Improve capability and business performance.</h3><Link href="/corporate-training">Train your team <ArrowRight /></Link></article></div></section>
  <section className="consulting section"><div><span className="eyebrow">Consulting services</span><h2>More than training.</h2><p>We help organisations use data, systems and financial information more effectively.</p><Link className="button button-light" href="/consulting">Discuss your business <ArrowRight /></Link></div><div className="service-list">{["Business process improvement","Data analysis & reporting","Systems & workflow optimisation","Financial & operational consulting","Dashboard development","Custom business solutions"].map((s,i)=><span key={s}><b>0{i+1}</b>{s}</span>)}</div></section>
  <section className="process section"><h2>From choosing a course to using the skill.</h2><ol>{["Choose your course","Register","Attend training","Complete practical exercises","Receive your certificate"].map((s,i)=><li key={s}><b>0{i+1}</b><span>{s}</span></li>)}</ol></section>
  <section className="impact"><div><h2>Invest in skills.<br/>Reap growth.</h2><p>Make better decisions. Work faster. Understand your data. Build stronger businesses.</p></div><ChartLineUp weight="thin" /></section>
  <section className="faq section"><div><span className="eyebrow">Common questions</span><h2>What to know before you register.</h2></div><div>{[["Do you offer online training?","Yes, both online and physical training are available."],["Where are physical classes held?","Harare, Zimbabwe."],["Do I need prior experience?","It depends on the course. Beginner-friendly options are available."],["Do you offer corporate training?","Yes. Training can be customised for organisations and teams."],["Will I receive a certificate?","Certificates of completion are available for eligible programmes."],["How do I register?","Contact Fulcrum via WhatsApp or the enquiry form."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta section"><span>Knowledge is leverage.</span><h2>Your growth.<br/>Our Fulcrum.</h2><p>Build practical skills that create better opportunities, stronger careers and smarter businesses.</p><div className="actions"><Link className="button" href="/contact">Book your training <ArrowRight /></Link><a className="text-link" href={wa}>WhatsApp us</a></div></section>
 </main>
}
function DataLever(){return <div className="hero-visual reveal"><div className="grid-plane"/><div className="chart-sheet"><div className="sheet-top"><span>LEARNING / OUTCOMES</span><b>Q3</b></div><div className="metric"><span>SKILL CONFIDENCE</span><strong>84<small>%</small></strong></div><svg viewBox="0 0 400 160" role="img" aria-label="Rising learning outcomes chart"><polyline points="0,140 70,128 130,108 195,112 260,72 320,86 400,18"/><line x1="0" y1="140" x2="400" y2="140"/></svg><div className="sheet-foot"><span>EXCEL</span><span>POWER BI</span><span>SQL</span></div></div><div className="credential"><Certificate/><b>Practical training</b><span>Real projects<br/>Guided learning<br/>Certificate</span></div></div>}
