import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, ChartLineUp, Certificate, MonitorPlay, ChalkboardTeacher, MapPin, Laptop } from "@phosphor-icons/react/dist/ssr";
import { courses } from "@/data/courses";
import { CourseCard } from "@/components/CourseCard";

const wa = "https://wa.me/263778599227?text=Hello%20Fulcrum%2C%20I%27d%20like%20to%20book%20training.";
export default function Home() {
 return <main id="main">
  <section className="hero education-hero"><div className="hero-copy reveal"><span className="eyebrow">Professional training in Harare and online</span><h1>Learn practical skills. <em>Use them with confidence.</em></h1><p>Instructor-led training in Excel, Power BI, SQL, accounting and business systems, built around the work you need to do.</p><div className="actions"><Link className="button" href="/courses">Browse programmes <ArrowRight /></Link><Link className="text-link" href="/contact">Speak to an advisor</Link></div><div className="hero-proof"><span><Certificate weight="fill"/> Certificate on eligible programmes</span><span><MapPin weight="fill"/> Harare + online</span></div></div><AcademyVisual /></section>
  <section className="trust-strip education-strip" aria-label="Training benefits"><span><ChalkboardTeacher /> Instructor-led</span><span><Laptop /> Online + physical</span><span><ChartLineUp /> Practical projects</span><span><Certificate /> Completion certificates</span></section>
  <section className="section courses-home"><div className="section-intro"><span className="eyebrow">Popular training</span><h2>Build skills that move your career forward.</h2><p>Practical courses designed around tools businesses actually use.</p></div><div className="course-list">{courses.slice(0,3).map((c,i)=><CourseCard key={c.slug} course={c} featured={i===1}/>)}</div><Link className="text-link arrow-link" href="/courses">View all seven courses <ArrowRight /></Link></section>
  <section className="learning-promise section"><div className="promise-heading"><span className="eyebrow">The Fulcrum learning model</span><h2>Learn it.<br/>Practise it.<br/><em>Apply it.</em></h2></div><div className="promise-steps"><article><span>01</span><h3>Clear instruction</h3><p>Build understanding with guided, instructor-led lessons.</p></article><article><span>02</span><h3>Hands-on practice</h3><p>Work through exercises using the software and systems you are learning.</p></article><article><span>03</span><h3>Work-ready outcomes</h3><p>Leave with practical capability you can use in study, work or business.</p></article></div></section>
  <section className="category-section section"><div className="category-title"><h2>One catalogue.<br/>Four ways forward.</h2><p>Choose the skill family that matches the work you want to do next.</p></div><div className="category-ledger"><div><b>Data & Analytics</b><span>Power BI / Excel / SQL</span></div><div><b>Accounting & Finance</b><span>QuickBooks / Pastel Partner</span></div><div><b>Payroll</b><span>Belina Payroll</span></div><div><b>Digital Skills</b><span>Computer applications</span></div></div></section>
  <section className="power-section section"><div className="power-copy"><span className="eyebrow">Power BI course</span><h2>Turn data into powerful insights.</h2><p>Learn how to connect, model, visualise and communicate data through hands-on exercises and real-world projects.</p><ul>{courses[1].topics.map(t=><li key={t}><Check />{t}</li>)}</ul><div className="price-lockup"><strong>US$85</strong><span>Course fee<br/>+ US$10 registration</span></div><Link className="button" href="/courses/power-bi">Register for Power BI <ArrowRight /></Link></div><div className="bi-visual" aria-label="Abstract Power BI dashboard showing rising business metrics"><div className="bi-head"><span>PERFORMANCE OVERVIEW</span><b>FULCRUM / BI</b></div><div className="bi-kpi"><small>Monthly output</small><strong>+28.4%</strong></div><div className="bar-chart">{[42,66,54,78,63,91,84].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div><div className="bi-note">FROM RAW DATA<br/><b>TO CLEAR DECISIONS</b></div></div></section>
  <section className="why section"><div className="why-lead"><h2>Why learn with Fulcrum?</h2><p>Every session is built to shorten the distance between knowing and doing.</p></div><div className="why-list">{[["Practical first","Hands-on sessions using real-world applications."],["Experienced instructors","Learn from professionals with industry experience."],["Flexible learning","Choose physical or online training."],["Real projects","Practise on realistic business scenarios."],["Certification","Certificates for eligible courses."],["Career value","Develop skills employers and businesses use."]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="audiences section"><h2>Training that meets you where you are.</h2><div className="audience-grid"><article><span>Students</span><h3>Build strong, in-demand skills for the future.</h3><Link href="/courses">Find your course <ArrowRight /></Link></article><article><span>Professionals</span><h3>Upgrade your skills and accelerate your career.</h3><Link href="/courses">Explore training <ArrowRight /></Link></article><article><span>Corporate teams</span><h3>Improve capability and business performance.</h3><Link href="/corporate-training">Train your team <ArrowRight /></Link></article></div></section>
  <section className="consulting section"><div><span className="eyebrow">Consulting services</span><h2>More than training.</h2><p>We help organisations use data, systems and financial information more effectively.</p><Link className="button button-light" href="/consulting">Discuss your business <ArrowRight /></Link></div><div className="service-list">{["Business process improvement","Data analysis & reporting","Systems & workflow optimisation","Financial & operational consulting","Dashboard development","Custom business solutions"].map((s,i)=><span key={s}><b>0{i+1}</b>{s}</span>)}</div></section>
  <section className="process section"><h2>From choosing a course to using the skill.</h2><ol>{["Choose your course","Register","Attend training","Complete practical exercises","Receive your certificate"].map((s,i)=><li key={s}><b>0{i+1}</b><span>{s}</span></li>)}</ol></section>
  <section className="impact"><div><h2>Invest in skills.<br/>Reap growth.</h2><p>Make better decisions. Work faster. Understand your data. Build stronger businesses.</p></div><ChartLineUp weight="thin" /></section>
  <section className="faq section"><div><span className="eyebrow">Common questions</span><h2>What to know before you register.</h2></div><div>{[["Do you offer online training?","Yes, both online and physical training are available."],["Where are physical classes held?","Harare, Zimbabwe."],["Do I need prior experience?","It depends on the course. Beginner-friendly options are available."],["Do you offer corporate training?","Yes. Training can be customised for organisations and teams."],["Will I receive a certificate?","Certificates of completion are available for eligible programmes."],["How do I register?","Contact Fulcrum via WhatsApp or the enquiry form."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta section"><span>Knowledge is leverage.</span><h2>Your growth.<br/>Our Fulcrum.</h2><p>Build practical skills that create better opportunities, stronger careers and smarter businesses.</p><div className="actions"><Link className="button" href="/contact">Book your training <ArrowRight /></Link><a className="text-link" href={wa}>WhatsApp us</a></div></section>
 </main>
}
function AcademyVisual(){return <div className="academy-visual reveal"><div className="academy-image"><Image src="/fulcrum-training-classroom.png" alt="Instructor guiding adult learners through practical business software training" fill priority sizes="(max-width: 760px) 100vw, 54vw"/></div><div className="academy-caption"><span>Practical learning</span><strong>Guided by instructors.<br/>Built around real work.</strong></div><div className="academy-mark"><b>F</b><span>Knowledge<br/>is leverage.</span></div></div>}
